services:
  - type: web
    name: blockcity
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: blockcity-db
          property: connectionString
      - key: NEXT_PUBLIC_DYNAMIC_ENVIRONMENT_ID
        sync: false
      - key: DYNAMIC_API_KEY
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false
      - key: BITCOIN_NETWORK
        value: mainnet
      - key: NEXT_PUBLIC_BITCOIN_NETWORK
        value: mainnet
      - key: NEXTAUTH_SECRET
        generateValue: true

databases:
  - name: blockcity-db
    databaseName: blockcity
    plan: starter

